<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>大文件上传报错 on ColorfulDark Blog</title>
    <link>https://www.harddone.com/tags/%E5%A4%A7%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0%E6%8A%A5%E9%94%99/</link>
    <description>Recent content in 大文件上传报错 on ColorfulDark Blog</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>zh-CN</language>
    <lastBuildDate>Mon, 15 Mar 2021 11:08:08 +0800</lastBuildDate><atom:link href="https://www.harddone.com/tags/%E5%A4%A7%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0%E6%8A%A5%E9%94%99/index.xml" rel="self" type="application/rss+xml" />
    <item>
      <title>Git：上传大文件报错解决方法</title>
      <link>https://www.harddone.com/post/git_big_file_err/</link>
      <pubDate>Mon, 15 Mar 2021 11:08:08 +0800</pubDate>
      
      <guid>https://www.harddone.com/post/git_big_file_err/</guid>
      <description>问题描述： git本地仓库提交之后，向远程仓库推送时报错,提示大文件问题。 error: pack-objects died of signal 13 error: failed to push some refs to &#39;git@github.com:example/example.git&#39; 在stackoverflow,找到解决方案提示是因为文件大小限制导致。 所以就直接到已提交到本地仓库的找到大文件xxx.hrpof，然后删除后立马又提交了本地仓库。但是推送的时候依然</description>
    </item>
    
  </channel>
</rss>
